# Based on: https://github.com/ibm-functions/runtime-python/tree/master/python3.6

FROM ibmfunctions/action-python-v3.6:master

RUN pip install cpyImagingMSpec==0.3.2
RUN pip install pandas==0.24.1
RUN pip install pyImagingMSpec==0.1.4
RUN pip install pyMSpec==0.1.2
RUN pip install cpyMSpec==0.4.2
RUN pip install pyimzML==1.2.5
RUN pip install msgpack-numpy
