FROM lithopscloud/ibmcf-python-v38

RUN pip install --no-cache-dir \
        # Modules for annotation-pipeline (These should match setup.py)
        pandas==1.1.3 \
        pyarrow==1.0.1 \
        scipy==1.5.3 \
        pyImagingMSpec==0.1.4 \
        cpyImagingMSpec==0.2.4 \
        pyMSpec==0.1.2 \
        cpyMSpec==0.3.5 \
	    pyimzML==1.4.1 \
        requests==2.22.0 \
        msgpack==0.6.2 \
        msgpack-numpy==0.4.4.3 \
	    pypng==0.0.19
